#!/bin/bash
# Hiddify Manager Full Install Script
# Author: Generated by ChatGPT
# Date: 2025-09-06

# Step 0: Update & install dependencies
echo "Updating system and installing required packages..."
sudo apt update && sudo apt upgrade -y
sudo apt install -y curl wget git ufw software-properties-common

# Step 1: Set up firewall
echo "Configuring basic firewall rules..."
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw --force enable

# Step 2: Download Hiddify installer
echo "Downloading Hiddify Manager installer..."
wget https://raw.githubusercontent.com/hiddify/hiddify-manager/main/install.sh -O install.sh
chmod +x install.sh

# Step 3: Run installer
echo "Running Hiddify Manager installer..."
sudo ./install.sh

# Step 4: Enable & start services
echo "Enabling Hiddify services..."
sudo systemctl enable hiddify-panel
sudo systemctl enable hiddify-haproxy
sudo systemctl start hiddify-panel
sudo systemctl start hiddify-haproxy

# Step 5: Check service status
echo "Checking service status..."
sudo systemctl status hiddify-panel
sudo systemctl status hiddify-haproxy

# Step 6: Final info
echo "Hiddify Manager installation complete!"
echo "Access your panel at: https://YOUR_DOMAIN_OR_IP/"
echo "Make sure your domain resolves to this server and ports 80/443 are open."
